### ISSUE TITLE
ToDo Bugs

### ISSUE THREAD

**Issue by Murthy10** [Sebubu/BringToAfrica#14]
- [x] Projekt erfassen, Datum Felder
- [x] Validierung Client- und Serverseitig
- [x] Projekt Widget, alle Bilder gleich gross / hoch
- [x] News View rückt ein
- [x] Mein Profil nicht anzeigen (wenn nicht eingeloggt)
- [x] Profileinstellungen Checkbox Password ändern grösser

**Comment by lukasmartinelli** [comment]
- [ ] Newsübersicht verrutscht das Bild

**Comment by Sebubu** [comment]
ProjectWidget - Prozentsatz geht nicht zurück
![blaaa](http://www11.pic-upload.de/30.04.15/wmxd342svtqx.png)

**Comment by manuelroth** [comment]
- [ ] News Seitenleiste ist am unteren Ende des Detailansicht
![bildschirmfoto 2015-05-01 um 10 56 30](https://cloud.githubusercontent.com/assets/1810384/7428443/023d06ca-eff1-11e4-9331-3b6562affeae.png)

**Comment by manuelroth** [comment]
-[ ] Letztes Widget in Projektübersicht ist auf der linken Seite, statt der rechten.

**Comment by manuelroth** [comment]
- [ ] Projektdetail Ansicht Progressbar ist teils länger als Bild

**Comment by manuelroth** [comment]
- [ ] Profileinstellungen Footer ist nicht am unteren Ende des Bildschirms

![bildschirmfoto 2015-05-03 um 17 40 53](https://cloud.githubusercontent.com/assets/1810384/7445630/a71365e2-f1bb-11e4-8f02-0424400f11bf.png)

**Comment by manuelroth** [comment]
- [ ] Spenden erfassen - Es kann nur immer eine Zahl über alle Kategorien ausgewählt werden

**Comment by lukasmartinelli** [comment]
>  Projekt Widget, alle Bilder gleich gross / hoch
Die Bilder waren glaub ich nicht das Problem sondern die Beschreibung, ich habe für diese einfach eine Minimalhöhe gesetzt, wir müssen dort aber noch die Beschreibung abschneiden nach einer gewissen Anzahl Zeichen
- [ ] Beschreibung zuschneiden für Projekt Widget

**Comment by Sebubu** [comment]
> Projekt Widget, alle Bilder gleich gross / hoch

Bildergrösse habe ich schon angepasst

**Comment by Murthy10** [comment]
- [ ] Servervalidierung überdeckt in Mobileansicht dir Buttons (bsp. Login)

**Comment by Sebubu** [comment]
- [ ] Projekt erstellen: Mehrere Spendenpunkte werden nicht übernommen (Bsp. 5 Katzen, 10 Hunde --> nur die Katzen werden eingetragen)
- [ ] Profileinstellungen: +-Button defekt

**Comment by manuelroth** [comment]
- [ ] News erfassen: Wenn Backend Validierung gemacht wird (Short-Link), wird nur Form gerendert ohne CSS.

**Comment by manuelroth** [comment]
- [ ] Spenden erfassen: Felder werden nicht validiert

**Comment by lukasmartinelli** [comment]
- [ ] Bilder wieder nicht mehr gleich hoch -> mein CSS hack hat irgendwie seine Magie verloren in den letzten Commits

**Comment by lukasmartinelli** [comment]
> Projekt erstellen: Mehrere Spendenpunkte werden nicht übernommen (Bsp. 5 Katzen, 10 Hunde --> nur die Katzen werden eingetragen)

Konnte ich irgendwie nicht reproduzieren.

**Comment by lukasmartinelli** [comment]
Manuel hett de Gott CSS Bug gfunde. Etz tuet alles wieder..
